### ISSUE TITLE
[Duplicate Selected Notes] Error

### ISSUE THREAD

**Issue by lanamacdo** [glutanimate/anki-addons-misc#140]
[Duplicate Selected Notes] Error

- [ x] In case of a bug: Have you tried restarting Anki?
- [x ] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [ x] Did you check the add-on description on AnkiWeb for known issues?
- [x ] Did you perform a cursory search through existing issue reports?

Debug info:
Anki 2.1.20 (47a1bf8b) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-06-30 19:54:31

Caught exception:
Traceback (most recent call last):
  File "C:\Users\lanam\AppData\Roaming\Anki2\addons21\2126361512\browser_create_duplicate.py", line 97, in <lambda>
    a.triggered.connect(lambda _, b=self: onCreateDuplicate(b))
  File "C:\Users\lanam\AppData\Roaming\Anki2\addons21\2126361512\browser_create_duplicate.py", line 100, in onCreateDuplicate
    createDuplicate(self)
  File "C:\Users\lanam\AppData\Roaming\Anki2\addons21\2126361512\browser_create_duplicate.py", line 79, in createDuplicate
    note_copy.flush()
  File "lib\site-packages\anki\notes.py", line 85, in flush
IndexError: list index out of range

Version 2.1.20 (47a1bf8b)

**System**

- Operating system: [ Windows]
- Version: [ 10 ]

**Comment by lanamacdo** [comment]
It was an Anki update problem after all... working now!
