### ISSUE TITLE
[Duplicate Selected Notes] broken in 2.1.28

### ISSUE THREAD

**Issue by ijgnd** [glutanimate/anki-addons-misc#147]
## Prerequisite checklist

- [x] In case of a bug: Have you tried restarting Anki?
- [x] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [x] Did you check the add-on description on AnkiWeb for known issues?
- [x] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented? / How can we reproduce the problem? / What were you doing when the problem occurred?

In 2.1.28 or 29 (Linux, no other add-ons used) when in the browser I click Edit->Create Duplicate I directly get this error (and no note seems to be added). Anki 2.1.28 is the first version where it occurs, in 2.1.26 I don't get it.

    Anki 2.1.28 (116aeead) Python 3.8.1 Qt 5.15.0 PyQt 5.15.0
    Platform: Linux
    Flags: frz=True ao=True sv=1
    Add-ons possibly involved: ⁨Duplicate Selected Notes⁩

    Caught exception:
    Traceback (most recent call last):
    File "/home/ijgnd/.local/share/Anki2/addons21/2126361512/browser_create_duplicate.py", line 104, in <lambda>
        a.triggered.connect(lambda _, b=self: onCreateDuplicate(b))
    File "/home/ijgnd/.local/share/Anki2/addons21/2126361512/browser_create_duplicate.py", line 108, in onCreateDuplicate
        createDuplicate(self)
    File "/home/ijgnd/.local/share/Anki2/addons21/2126361512/browser_create_duplicate.py", line 67, in createDuplicate
        o = mw.col.decks.get(deck)
    File "anki/decks.py", line 194, in get
    TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

In your source code you have `mw.col.decks.get(deck)['mid'] = model['id']`. `decks.get` usually takes an id and not a dict, so with this line `mw.col.decks.get(deck['id'])['mid'] = model['id']` I get no error message but I haven't tested what else this means.

The open pull request at https://github.com/glutanimate/anki-addons-misc/pull/136/commits/4478af6efd685cbbfd692b2fd3e9df2b288baaa2 also means that no error message appears.

With your version and the pull request in Anki 2.1.28 you still have:

    Traceback (most recent call last):
    File "/home/ijgnd/.local/share/Anki2/2126361512/browser_create_duplicate.py", line 104, in <lambda>
        a.triggered.connect(lambda _, b=self: onCreateDuplicate(b))
    File "/home/ijgnd/.local/share/Anki2/2126361512/browser_create_duplicate.py", line 108, in onCreateDuplicate
        createDuplicate(self)
    File "/home/ijgnd/.local/share/Anki2/2126361512/browser_create_duplicate.py", line 86, in createDuplicate
        note_copy.flush()
    File "anki/notes.py", line 67, in flush

So I just commented out the .flush line in your add-on.

&nbsp;

&nbsp;

In older Anki versions with the code you have on Ankiweb I also got these errors (I haven't tested with the pull request):

In the editor of an Add window I get the following error like this: Use the Add window, keep it open. Go to the browser, duplicate another note type, then back in the add window try to close it. The error disappears if I set another note type in the Add window and then close it.

    Anki 2.1.24 (359b9f5c) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
    Platform: Linux
    Flags: frz=True ao=True sv=1

    Caught exception:
    Traceback (most recent call last):
    File "aqt/webview.py", line 464, in handler
    File "aqt/editor.py", line 475, in <lambda>
    File "aqt/addcards.py", line 244, in afterSave
    File "aqt/editor.py", line 503, in fieldsAreBlank
    IndexError: list index out of range

In Anki 2.1.26 sometimes I don't get an error or I get this one (e.g. when I try to search in the browser):

    Anki 2.1.26 (70784154) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
    Platform: Linux
    Flags: frz=True ao=True sv=1

    Caught exception:
    Traceback (most recent call last):
    File "aqt/progress.py", line 43, in handler
    File "aqt/browser.py", line 863, in <lambda>
    File "aqt/browser.py", line 879, in _onRowChanged
    File "aqt/editor.py", line 425, in setNote
    File "aqt/editor.py", line 439, in loadNote
    File "anki/notes.py", line 141, in items
    File "anki/notes.py", line 141, in <listcomp>
    IndexError: list index out of range

## Version information
   
    Anki 2.1.28 (116aeead) Python 3.8.1 Qt 5.15.0 PyQt 5.15.0
    Platform: Linux
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-07-29 10:29:39
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Duplicate Selected Notes ['2126361512', 2017-08-29T20:57, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    2126361512
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])

**Comment by DentalGeek** [comment]
Having issues with 2.1.33
I get this error when pressing  ⌥ ⌘Z to duplicate the notes. I have followed all of the prerequisites listed on the checklist. This is my first time posting anything like this so bear with me. This add-on was a lifesaver and I desperately need it for school. 


Debug info:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-09-11 14:48:31
Add-ons possibly involved: ⁨Duplicate Selected Notes⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/1/Library/Application Support/Anki2/addons21/2126361512/browser_create_duplicate.py", line 97, in <lambda>
    a.triggered.connect(lambda _, b=self: onCreateDuplicate(b))
  File "/Users/1/Library/Application Support/Anki2/addons21/2126361512/browser_create_duplicate.py", line 100, in onCreateDuplicate
    createDuplicate(self)
  File "/1/Library/Application Support/Anki2/addons21/2126361512/browser_create_duplicate.py", line 64, in createDuplicate
    mw.col.decks.get(deck)['mid'] = model['id']
  File "anki/decks.py", line 209, in get
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

**Comment by volindsay** [comment]
In Windows, I am having what seems to be this same issue. I am not able to duplicate from one deck to another.

**Comment by thiswillbeyourgithub** [comment]
I may have found a fix, see this message : https://github.com/glutanimate/anki-addons-misc/issues/155#issuecomment-696672889
