### ISSUE TITLE
[Duplicate Selected Notes] broken in 2.1.33

### ISSUE THREAD

**Issue by sasadangelo** [glutanimate/anki-addons-misc#155]
## Which add-on is affected?

[ Duplicate Selected Notes]

## Prerequisite checklist

- [X ] In case of a bug: Have you tried restarting Anki?
- [ X] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [X ] Did you check the add-on description on AnkiWeb for known issues?
- [ X] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

I got this exception when I try to duplicate 1 card.
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-09-20 09:50:25
Add-on che possono essere coinvolti: ⁨Duplicate Selected Notes⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/sasadangelo/Library/Application Support/Anki2/addons21/2126361512/browser_create_duplicate.py", line 97, in <lambda>
    a.triggered.connect(lambda _, b=self: onCreateDuplicate(b))
  File "/Users/sasadangelo/Library/Application Support/Anki2/addons21/2126361512/browser_create_duplicate.py", line 100, in onCreateDuplicate
    createDuplicate(self)
  File "/Users/sasadangelo/Library/Application Support/Anki2/addons21/2126361512/browser_create_duplicate.py", line 64, in createDuplicate
    mw.col.decks.get(deck)['mid'] = model['id']
  File "anki/decks.py", line 209, in get
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

## How can we reproduce the problem?

1. Work on Anki 2.1.33
2. Install the latest version of the add
3. try to duplicate a card

**Expected behavior:** 

Card duplicated

**Actual behavior:**

Exception above

**Reproducible?:**

In my env, it is reproduced continuously.

## Version information

**Anki**

2.1.33
Python 3.8.0 Qt 5.14.2 PyQt 5.14.2

**System**

- macOS
- Version: Catalina

**Comment by sasadangelo** [comment]
The problem seems similar to https://github.com/glutanimate/anki-addons-misc/issues/147 but I noticed some differences in the stack trace so I am not sure if it is exactly the same problem.
You can remove the issue if it is a duplicate.

**Comment by thiswillbeyourgithub** [comment]
I seem to have found a fix.
Here's a link to the relevant PR and the relevant commit (it's just a line swap) :
PR : https://github.com/glutanimate/anki-addons-misc/pull/156
commit : https://github.com/glutanimate/anki-addons-misc/pull/156/commits/6249295b72b065432154a7cc48b6c488db5ff511

**Comment by sasadangelo** [comment]
Hi @thiswillbeyourgithub ,

Thank you for your reply. I applied the fix but it didn't work for me. I use Mac and below the debug message that seems always the same.

Here what I did. Downloaded the add-on in Anki and restart it.
Then Tools->Addon->Show Files. In the file browser_create_duplicate.py I swapped this lines in this way:

```
        # Refresh note and add to database
        mw.col.addNote(note_copy)
        note_copy.flush()
```

Restart Anki again. Then Open Anki->Browse select a card and try to duplicate it with Edit->Create Duplicate.

Here the stack trace:
Anki 2.1.33 (3f403040) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.6
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-10-01 08:25:58
Add-on che possono essere coinvolti: ⁨Duplicate Selected Notes⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/sasadangelo/Library/Application Support/Anki2/addons21/2126361512/browser_create_duplicate.py", line 97, in <lambda>
    a.triggered.connect(lambda _, b=self: onCreateDuplicate(b))
  File "/Users/sasadangelo/Library/Application Support/Anki2/addons21/2126361512/browser_create_duplicate.py", line 100, in onCreateDuplicate
    createDuplicate(self)
  File "/Users/sasadangelo/Library/Application Support/Anki2/addons21/2126361512/browser_create_duplicate.py", line 64, in createDuplicate
    mw.col.decks.get(deck)['mid'] = model['id']
  File "anki/decks.py", line 209, in get
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

**Comment by sasadangelo** [comment]
I fixed your problem with your fix + this commit https://github.com/zlodag/anki-addons-misc/commit/4478af6efd685cbbfd692b2fd3e9df2b288baaa2

I basically browsed all the fork to check what other users did.
To be honest I didn't analyze why it worked because I don't have time to debug it, however with these two fixes it works.

**Comment by wildmed** [comment]
I'm not a coder, so I don't know how to address this problem or if there is another add-on or script I am missing that must be in place to allow this one to function properly.
Thank you for your help.
------------------------------------------
Similar error:

Debug info:
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Mac 10.15.7
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-10-22 06:57:51
Add-ons possibly involved: ⁨Duplicate Selected Notes⁩

Caught exception:
Traceback (most recent call last):
  File "/Users/mark/Library/Application Support/Anki2/addons21/2126361512/browser_create_duplicate.py", line 97, in <lambda>
    a.triggered.connect(lambda _, b=self: onCreateDuplicate(b))
  File "/Users/mark/Library/Application Support/Anki2/addons21/2126361512/browser_create_duplicate.py", line 100, in onCreateDuplicate
    createDuplicate(self)
  File "/Users/mark/Library/Application Support/Anki2/addons21/2126361512/browser_create_duplicate.py", line 64, in createDuplicate
    mw.col.decks.get(deck)['mid'] = model['id']
  File "anki/decks.py", line 214, in get
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'

**Comment by dreumann222** [comment]
I know nothing about programming and only joined GitHub because I was advised to report a bug with the Duplicate Selected Notes addon at this site.  This addon has not worked since, I believe, 3 updates ago.  I used to use this extensively and would really welcome a fix.  Here is the error code I keep receiving:

Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-10-24 05:35:44

Caught exception:
Traceback (most recent call last):
  File "C:\Users\ASUS\AppData\Roaming\Anki2\addons21\2126361512\browser_create_duplicate.py", line 97, in <lambda>
    a.triggered.connect(lambda _, b=self: onCreateDuplicate(b))
  File "C:\Users\ASUS\AppData\Roaming\Anki2\addons21\2126361512\browser_create_duplicate.py", line 100, in onCreateDuplicate
    createDuplicate(self)
  File "C:\Users\ASUS\AppData\Roaming\Anki2\addons21\2126361512\browser_create_duplicate.py", line 64, in createDuplicate
    mw.col.decks.get(deck)['mid'] = model['id']
  File "anki\decks.py", line 214, in get
TypeError: int() argument must be a string, a bytes-like object or a number, not 'dict'


Thanks for any help you can provide (but please don't tell me to program anything as I would have no idea what to do).

**Comment by kirbizzle** [comment]
This fix worked for me as well. For those not familiar with editing code, here is (hopefully) an easy to follow guide:

1. Open Anki and select Tools -> Add Ons
2. Select "Duplicate Selected Notes" so it is highlighted and choose the "View Files" button to the right.
3. Open up "browser_create_duplicate.py" - you can open it with Notpad, Sublime whatever
4. Go [here](https://github.com/zlodag/anki-addons-misc/blob/4478af6efd685cbbfd692b2fd3e9df2b288baaa2/src/browser_create_duplicate/browser_create_duplicate.py) -> select all the text (CTRL + A) -> Copy it all
5. Go back to your open **browser_create_duplicate.py** -> select all the text (CTRL + A) -> delete & paste the code you copied from step 4
6. Come back here and copy the text below that was posted by @sasadangelo 
```ruby
        # Refresh note and add to database
        mw.col.addNote(note_copy)
        note_copy.flush()
``` 
7. Go back into **browser_create_duplicate.py** and scroll down to line ~65 and you will find:
```ruby
# Refresh note and add to database
``` 

8. Highlight # Refresh note and add to database _and the two lines of code below it_ -> delete & replace with the code you copied in step 6.
9. Save the file -> Restart Anki and you should be good to go!!

**Comment by dreumann222** [comment]
Your instructions were very clear and it worked like a charm...thank you so
very much.

**Comment by jatubio** [comment]
> This fix worked for me as well. For those not familiar with editing code, here is (hopefully) an easy to follow guide:
> 
....

Thank you very much. It worked for me too!

**Comment by lanamacdo** [comment]
Here's the exception blocking me from using this add-on.  I tried the above fix but it didn't work for me.  

Debug info:
Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2022-09-06 11:38:21

Caught exception:
Traceback (most recent call last):
  File "C:\Users\lanam\AppData\Roaming\Anki2\addons21\2126361512\browser_create_duplicate.py", line 84, in <lambda>
    a.triggered.connect(lambda _, b=self: onCreateDuplicate(b))
  File "C:\Users\lanam\AppData\Roaming\Anki2\addons21\2126361512\browser_create_duplicate.py", line 87, in onCreateDuplicate
    createDuplicate(self)
  File "C:\Users\lanam\AppData\Roaming\Anki2\addons21\2126361512\browser_create_duplicate.py", line 52, in createDuplicate
    model = note._model
  File "anki\_legacy.py", line 52, in __getattr__
AttributeError
