### ISSUE TITLE
Insert Randomized Lists (multiple choice)

### ISSUE THREAD

**Issue by carlratcliffe** [glutanimate/anki-addons-misc#168]
## Insert Randomized Lists (multiple choice)

[ Please mention the add-on in the issue title as follows: "[Add-on name] My issue" ]

## Prerequisite checklist

[ Please enter an [ x ] character to confirm the points below: ]

- [x] In case of a bug: Have you tried restarting Anki?
- [x] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [x] Did you check the add-on description on AnkiWeb for known issues?
- [x] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

[ Please be as specific as possible. Provide screenshots if you think they can help. ]

## How can we reproduce the problem?

Invalid HTML on card: SyntaxError: Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
at JSON.parse ()
at run (eval at (http://127.0.0.1:59710/_anki/jquery.js:2:2651), :70:36)
at eval (eval at (http://127.0.0.1:59710/_anki/jquery.js:2:2651), :76:1)
at eval ()
at http://127.0.0.1:59710/_anki/jquery.js:2:2651
at Function.globalEval (http://127.0.0.1:59710/_anki/jquery.js:2:2662)
at Ha (http://127.0.0.1:59710/_anki/jquery.js:3:21262)
at n.fn.init.append (http://127.0.0.1:59710/_anki/jquery.js:3:22791)
at n.fn.init. (http://127.0.0.1:59710/_anki/jquery.js:3:24070)
at Y (http://127.0.0.1:59710/_anki/jquery.js:3:4515)

**Comment by NameLessGO** [comment]
My experience with this bug
1. was using this on .36 (bcz of the 40+ add-ons)
2. hop into the .42 to check the new update 
3. returned to .36 (downgrade & quit) because of the reason on 1. 
4. the cards created using this add-ons was with the bug mentioned above
5. hop back into the .42 and now the card is fine
