### ISSUE TITLE
create filtered deck from the browser - error 

### ISSUE THREAD

**Issue by sarahlippinc** [glutanimate/anki-addons-misc#172]
I get this error when trying to create a filtered deck from browse:

Anki 2.1.42 (8eebfe18) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-03-11 14:02:31

Caught exception:
Traceback (most recent call last):
  File "C:\Users\boofalonius\AppData\Roaming\Anki2\addons21\861263371\browser_create_filtered_deck.py", line 31, in <lambda>
    a.triggered.connect(lambda _, b=self: createFilteredDeck(b))
  File "C:\Users\boofalonius\AppData\Roaming\Anki2\addons21\861263371\browser_create_filtered_deck.py", line 24, in createFilteredDeck
    self.mw.onCram(search)
TypeError: onCram() takes 1 positional argument but 2 were given

**Comment by glutanimate** [comment]
Hi Sarah, 

Thanks for the detailed report! It looks like the add-on broke with the recent Anki 2.1.41 and 2.1.42 updates that were released last week. Will look into it and see if there is a viable fix.

**Comment by nitrogenase** [comment]
I encounter the same error with the current Version of Anki 2.1.44. Hopefully this can be fixed! :)

> Error
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
> If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
> When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
> Debug info:
> Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
> Platform: Mac 10.15.7
> Flags: frz=True ao=True sv=2
> Add-ons, last update check: 2021-07-12 12:35:33
> Add-ons possibly involved: ⁨Create Filtered Deck from the Browser⁩
> 
> Caught exception:
> Traceback (most recent call last):
>   File "/Users/hharbrecht/Library/Application Support/Anki2/addons21/861263371/browser_create_filtered_deck.py", line 31, in <lambda>
>     a.triggered.connect(lambda _, b=self: createFilteredDeck(b))
>   File "/Users/hharbrecht/Library/Application Support/Anki2/addons21/861263371/browser_create_filtered_deck.py", line 24, in createFilteredDeck
>     self.mw.onCram(search)
> TypeError: onCram() takes 1 positional argument but 2 were given

**Comment by nitrogenase** [comment]
I receive the same error with the current version of Anki 2.1.44. Hopefully this can be fixed! :)

> Error
> An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
> If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
> When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
> Debug info:
> Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
> Platform: Mac 10.15.7
> Flags: frz=True ao=True sv=2
> Add-ons, last update check: 2021-07-12 12:35:33
> Add-ons possibly involved: ⁨Create Filtered Deck from the Browser⁩
> 
> Caught exception:
> Traceback (most recent call last):
>   File "/Users/XXX/Library/Application Support/Anki2/addons21/861263371/browser_create_filtered_deck.py", line 31, in <lambda>
>     a.triggered.connect(lambda _, b=self: createFilteredDeck(b))
>   File "/Users/XXX/Library/Application Support/Anki2/addons21/861263371/browser_create_filtered_deck.py", line 24, in createFilteredDeck
>     self.mw.onCram(search)
> TypeError: onCram() takes 1 positional argument but 2 were given
>
