### ISSUE TITLE
[Insert Randomized Lists (multiple choice)] add-on broken on 2.1.41+3

### ISSUE THREAD

**Issue by NameLessGO** [glutanimate/anki-addons-misc#176]
## Which add-on is affected?

[ Please mention the add-on in the issue title as follows: "[Add-on name] My issue" ]

## Prerequisite checklist

[ Please enter an [ x ] character to confirm the points below: ]

- [x] In case of a bug: Have you tried restarting Anki?
- [x] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [x] Did you check the add-on description on AnkiWeb for known issues?
- [x] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?
would like to the add-on be updated to support 2.1.41+ features since they help me a lot with making practice questions into anki

[ Please be as specific as possible. Provide screenshots if you think they can help. ]

## How can we reproduce the problem?

[ What were you doing when the problem occurred? ]

1. [ was using the add-on on the .36 with the 40+ add-on by anking ]
2. [ Updated to 2.1.41+ (.43) ]
3. [ the add-on stopped working on the 2.1.41-> downgraded to 21.36 and the error persist ]

**Expected behavior:** [ What you expected to happen ]
randomized the questions (multiple choice)
**Actual behavior:** [ this error msg appears on the back ]
this appears on the back
Invalid HTML on card: SyntaxError: Unexpected end of JSON input
SyntaxError: Unexpected end of JSON input
at JSON.parse ()
at run (eval at (http://127.0.0.1:55601/_anki/js/vendor/jquery.js:2:2651), :69:36)
at eval (eval at (http://127.0.0.1:55601/_anki/js/vendor/jquery.js:2:2651), :75:1)
at eval ()
at http://127.0.0.1:55601/_anki/js/vendor/jquery.js:2:2651
at Function.globalEval (http://127.0.0.1:55601/_anki/js/vendor/jquery.js:2:2662)
at Ha (http://127.0.0.1:55601/_anki/js/vendor/jquery.js:3:21262)
at n.fn.init.append (http://127.0.0.1:55601/_anki/js/vendor/jquery.js:3:22791)
at n.fn.init. (http://127.0.0.1:55601/_anki/js/vendor/jquery.js:3:24070)
at Y (http://127.0.0.1:55601/_anki/js/vendor/jquery.js:3:4515)

**Reproducible?:** [ Can you reliably reproduce the issue by following the steps above? ]
Yes, use the add-on on .36 then update to .41+ and the error will persist even if  you downgrade and "reset the add-on" (recreate the card: front and back template + install cookie monster + insert randomizer...

## Version information
2.1.40
2.1.43
**Anki**

[ Version ⁨2.1.40 (cf446733)⁩ ]
[ Python 3.8.6 Qt 5.14.2 PyQt 5.14.2 ]

[  Version ⁨2.1.43 (0fbae6bc)⁩ ]
[ Python 3.8.6 Qt 5.14.2 PyQt 5.14.2 ]

**System**

- Operating system: [ Windows ]
- Version: [10 pro ]

**Comment by bwhurd** [comment]
It would be really great to have this working with the latest version of anki.  Will send a craft beer sized payment via patreon. lol. but seriously.

**Comment by bentyeh** [comment]
Here's a quick fix: #179

To apply the fix yourself (rather than wait for the addon to be officially updated by glutanimate):
1. Open Anki
2. Click Tools > Addons
3. Select this addon ("Insert Randomized Lists multiple choice")
4. Click "View Files"
5. Open editor_random_list.py in a text editor.
6. Apply the changes in #179.
7. Restart Anki.

**Comment by NameLessGO** [comment]
Thank you!, it works on 2.1.45 beta 5 as well

**Comment by awsaunier** [comment]
I tried the fix #179 above and it seems to be broken again in 2.1.49. I was unable to get the bullets to randomize.
