### ISSUE TITLE
[Create Filtered Deck from the Browser] Hotkey not working + error message when trying to use the addon

### ISSUE THREAD

**Issue by AmelieCM** [glutanimate/anki-addons-misc#178]
## Which add-on is affected?

Create Filtered Deck from the Browser

## Prerequisite checklist

- [x] In case of a bug: Have you tried restarting Anki?
- [x] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [x] Did you check the add-on description on AnkiWeb for known issues?
- [x] Did you perform a cursory search through existing issue reports?

My issue may be related to issues #166 and #161
It is similar but I have an error message when trying to use the edit menu (not mentioned there).

## What is the problem/feature you would like to see fixed/implemented?

The Create Filtered Deck addon is not working at all

## How can we reproduce the problem?

I installed the addon for the first time, opened the Browse window and tried to use it

**Expected behavior:**

Creation of a filtered deck based on the current view in the browser

**Actual behavior:**

Nothing happened with the hotkey Ctrl+Shift+D.

I tried "Create Filtered Decks based on this search" in the Edit menu
An error message popped up: 

```
Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-05-27 20:56:05

Caught exception:
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\861263371\browser_create_filtered_deck.py", line 31, in <lambda>
    a.triggered.connect(lambda _, b=self: createFilteredDeck(b))
  File "C:\Users\xxx\AppData\Roaming\Anki2\addons21\861263371\browser_create_filtered_deck.py", line 24, in createFilteredDeck
    self.mw.onCram(search)
TypeError: onCram() takes 1 positional argument but 2 were given
```

**Reproducible?:** 

Occurs every time for me :
- nothing happens with the hotkey
- error message with the menu item

## Version information

**Anki**

Here is my debug info :

```
    Anki 2.1.44 (b2b3275f) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
    Platform: Windows 10
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2021-05-27 20:56:05
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Table ['1237621971', 2020-07-25T14:19, 'None', mod]
    Create Filtered Deck from the Browser ['861263371', 2017-08-29T20:57, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2020-04-28T04:21, 'None', '']
    LPCG LyricsPoetry Cloze Generator ['2084557901', 2020-07-12T01:06, 'None', '']
    Mini Format Pack ['295889520', 2018-07-24T19:45, 'None', '']
    Review Heatmap ['review_heatmap', 2020-04-30T15:23, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1237621971 1374772155 2084557901 295889520 861263371
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
```

**System**

- Operating system: Windows
- Version: 10
- using PortableApps (portable version of Anki on an external hard drive)

**Comment by AmelieCM** [comment]
Sorry, I just found, but too late, issue #172 
Closing this now since it is the same
