### ISSUE TITLE
[Field history] error on trying to use history window

### ISSUE THREAD

**Issue by dawch** [glutanimate/anki-addons-misc#48]
Mac OS X 10.11.6
Anki Version 2.0.50
Qt 4.8.2 PyQt 4.9.4

When trying to invoke the field history add on with the command-O shortcut I get the below error 
Incidentally, and perhaps related, none of the other shortcut keys do anything

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
  File "/Users/chris/Library/Application Support/Anki2/addons/Field_History.py", line 149, in <lambda>
    t.activated.connect(lambda a=self: restoreEditorFields(a, "history"))
  File "/Users/chris/Library/Application Support/Anki2/addons/Field_History.py", line 127, in restoreEditorFields
    res = historyRestore(self, mode, sorted_res, model)
  File "/Users/chris/Library/Application Support/Anki2/addons/Field_History.py", line 68, in historyRestore
    if html.strip():
UnboundLocalError: local variable 'html' referenced before assignment

**Comment by glutanimate** [comment]
Hi @dawch,

Sorry for the late response, but Field History has been updates since you last reported this problem and I was wondering if you were still affected by it?

**Comment by glutanimate** [comment]
Closing this as Anki 2.0 is no longer supported.
