### ISSUE TITLE
Batch Remove Formatting (e.g. bold, italics, etc.) error.

### ISSUE THREAD

**Issue by oxk4r01** [glutanimate/anki-addons-misc#72]
## Which add-on is affected?

[ Batch Remove Formatting (e.g. bold, italics, etc.) ]

## Prerequisite checklist

[ Please enter an [ x ] character to confirm the points below: ]

- [x] In case of a bug: Have you tried restarting Anki?
- [x] Are you running the latest version of the add-on? Have you redownloaded the add-on from AnkiWeb to make sure?
- [x] Did you check the add-on description on AnkiWeb for known issues?
- [x] Did you perform a cursory search through existing issue reports?

## What is the problem/feature you would like to see fixed/implemented?

[ Please be as specific as possible. Provide screenshots if you think they can help. ]

## How can we reproduce the problem?

Addon not working. Throws this error:

An error occurred in an add-on.
Please post on the add-on forum:
https://anki.tenderapp.com/discussions/add-ons

Traceback (most recent call last):
File "D:\OSCAR\PortableApps\AnkiPortable\Data\ankidata\addons\Batch_Remove_Formatting_eg_bold_italics_etc.py", line 76, in <lambda>
a.triggered.connect(lambda _, b=browser: onClearFormatting(b))
File "D:\OSCAR\PortableApps\AnkiPortable\Data\ankidata\addons\Batch_Remove_Formatting_eg_bold_italics_etc.py", line 99, in onClearFormatting
note.fields = stripFormatting(note.fields)
File "D:\OSCAR\PortableApps\AnkiPortable\Data\ankidata\addons\Batch_Remove_Formatting_eg_bold_italics_etc.py", line 60, in stripFormatting
soup = BeautifulSoup(html, "html.parser")
File "thirdparty\BeautifulSoup.py", line 1521, in __init__
File "thirdparty\BeautifulSoup.py", line 1146, in __init__
File "thirdparty\BeautifulSoup.py", line 1188, in _feed
File "sgmllib.py", line 104, in feed
File "sgmllib.py", line 138, in goahead
File "sgmllib.py", line 296, in parse_starttag
File "sgmllib.py", line 338, in finish_starttag
File "thirdparty\BeautifulSoup.py", line 1343, in unknown_starttag
AttributeError: 'unicode' object has no attribute 'text' 
[ Version 2.0.36 portable ]
[ Qt 4.8.1 PyQt 4.9.1 ]

**System**

- Operating system: [ Windows ]
- Version: [ 10 ]

**Comment by ReflexivR** [comment]
I get the same exact error on Windows 7, Anki 2.0.52.

**Comment by glutanimate** [comment]
Thanks for the reports, guys. I can reproduce the issue here. Seems like it's limited to Anki 2.0. I will look into a fix soon, but in the meantime if you depend on the add-on or its functionality upgrading to Anki 2.1 might be a viable option.

@oxk4r01 Your Anki version is very old at Anki 2.0.36. You should definitely consider upgrading to Anki 2.0.52 at least, as add-on authors will be unlikely/unable to support Anki versions as early as this in the future.
